### ISSUE TITLE
Sugestão: Opção de clonagem

### ISSUE THREAD

**Issue by HelkerSuardi** [kolinalabs/mongoose-consistent#1]
Em algumas situações, precisamos manter algumas informações pertinentes a entidade relacionada, como por ex o nome da entidade, portanto, deixar nulo (que é a unica opção existente que te possibilita excluir a entidade relacionada e manter a entidade pai) pode causar problemas. 

Imagine a situação: voce tem a entidade venda que possui a entidade cliente, e ao excluir esse cliente, vc nao quer que a sua venda seja excluida, nao precisa gerar uma exception e muito menos deixar esse cliente como null.

Poderia existir no onDelete, um comando chamado CLONE por ex, onde o usuário passaria as props a qual ele deseja que sejam clonadas (ex: nome e endereço), ficando algo parecido com:
onDelete: 'clone{nome, endereço}'

Com isso, é necessário que a lib seja capaz de criar um atributo na entidade, já que a do tipo ObjectId não aceitará o clone obviamente, um atributo que pode ter o nome dinâmico. Usando o ex acima de vendas, ele geraria um atributo novo chamado clienteClone.

**Comment by cjchamado** [comment]
Obrigado pela sugestão @HelkerSuardi!

Você poderá utilizar a opção de callback (função) na configuração do evento e executar esse procedimento dentro da mesma.

```js
const OrderSchema = new mongoose.Schema({
    customer: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Customer',
        onDelete(context) {
            // O objeto "context" possui as informações necessárias para o procedimento
        }
    }
})
```

Vale lembrar que por questões de performance, o plugin executa apenas a contagem de documentos na checagem e não o carregamento dos mesmos na íntegra. No entanto, ao utilizar a função, o objeto "context" fornece os mesmos argumentos utilizados na contagem, com os quais é possível efetuar o carregamento dos registros e posteriormente efetuar o backup ou outras operações com os mesmos.

Desculpe pela demora, estava fazendo ☕ .
